### ISSUE TITLE
Deriv and clang

### ISSUE THREAD

**Issue by HedvigS** [sgsokol/Deriv#32]
I think there's a problem with the latest version of `Deriv` (`4.3.0`) and Apple's `clang` (`17.0.0`)

The compilation of derive_simplif.cpp fails with the following errors:
```
derive_simplif.cpp:376:28: error: use of undeclared identifier 'R_ClosureFormals'
derive_simplif.cpp:467:25: error: use of undeclared identifier 'Rf_allocLang'
```

Full error:

```
> renv::install("Deriv")
# Downloading packages -------------------------------------------------------
- Downloading Deriv 4.3.0 from CRAN ...         OK [file is up to date]
Successfully downloaded 1 package in 0.15 seconds.

The following package(s) will be installed:
- Deriv [4.3.0]
These packages will be installed into "~/Git/HedvigS/LingTyp_EvoTyp/code/renv/library/macos/R-4.4/aarch64-apple-darwin20".

Do you want to proceed? [Y/n]: y

# Installing packages --------------------------------------------------------
- Installing Deriv 4.3.0 ...                    FAILED
Error: Error installing package 'Deriv':
=================================

* installing *source* package ‘Deriv’ ...
** package ‘Deriv’ successfully unpacked and MD5 sums checked
** using staged installation
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
** libs
using C++ compiler: ‘Apple clang version 17.0.0 (clang-1700.0.13.5)’
using SDK: ‘MacOSX15.5.sdk’
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/skirgard/Git/HedvigS/LingTyp_EvoTyp/code/renv/library/macos/R-4.4/aarch64-apple-darwin20/Rcpp/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2   -c RcppExports.cpp -o RcppExports.o
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/skirgard/Git/HedvigS/LingTyp_EvoTyp/code/renv/library/macos/R-4.4/aarch64-apple-darwin20/Rcpp/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2   -c derive_simplif.cpp -o derive_simplif.o
derive_simplif.cpp:376:28: error: use of undeclared identifier 'R_ClosureFormals'
  376 |             SEXP formals = R_ClosureFormals(user_fun);
      |                            ^
derive_simplif.cpp:467:25: error: use of undeclared identifier 'Rf_allocLang'; did you mean 'Rf_allocList'?
  467 |     SEXP call = PROTECT(Rf_allocLang(n + 1));
      |                         ^~~~~~~~~~~~
      |                         Rf_allocList
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:371:31: note: expanded from macro 'PROTECT'
  371 | #define PROTECT(s)      Rf_protect(s)
      |                                    ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:487:6: note: 'Rf_allocList' declared here
  487 | SEXP Rf_allocList(int);
      |      ^
2 errors generated.
make: *** [derive_simplif.o] Error 1
ERROR: compilation failed for package ‘Deriv’
* removing ‘/Users/skirgard/Git/HedvigS/LingTyp_EvoTyp/code/renv/staging/1/Deriv’
install of package 'Deriv' failed [error code 1]
```

Installing `Deriv` version `4.1.3` succeeds.

System info:
```
> R.version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          4.0                         
year           2024                        
month          04                          
day            24                          
svn rev        86474                       
language       R                           
version.string R version 4.4.0 (2024-04-24)
nickname       Puppy Cup                   
> Sys.info()["version"] 
                                                                                                        version 
"Darwin Kernel Version 24.6.0: Mon Jan 19 21:59:23 PST 2026; root:xnu-11417.140.69.708.3~1/RELEASE_ARM64_T6030" 

> system("clang --version")
Apple clang version 17.0.0 (clang-1700.0.13.5)
Target: arm64-apple-darwin24.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

```

**Comment by sgsokol** [comment]
Thanks for reporting and sorry for annoyance.
The lastest version on github (4.3.1) works with minimal R v4.4.1. Your R installation 4.4.0 is just one bug fix release behind.
In the next release, I will percise the minimal R version in the DESCRIPTION file.

**Comment by HedvigS** [comment]
> Thanks for reporting and sorry for annoyance. The lastest version on github (4.3.1) works with minimal R v4.4.1. Your R installation 4.4.0 is just one bug fix release behind. In the next release, I will percise the minimal R version in the DESCRIPTION file.

aaaahaa, sorry! I'll see to that. Thanks!
